version: '3'
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=" "
  web:
    image: apache
    build: ./Travel
    depends_on:
        - db
    container_name: apache_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
